[gateway]
port=8081

[servicegroup]
port=8080
host="localhost"

[iotAgents]
port= 8082
host="localhost"
	[iotAgents.db]
	host="localhost"
	port=5432
	db="iot-agents"
	
[user]
port= 8084
host="localhost"
	[user.db]
	host="localhost"
	port=5432
	db="user"
[keyrock]
host="https://keyrock.solvita.eng-its.de"

