// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iotAgents.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	iotAgents.proto
	serviceGroups.proto

It has these top-level messages:
	IotAgent
	AddIotAgentRequest
	ListIotAgentsResponse
	GetIotAgentWithProtocolRequest
	GetIotAgentWithProtocolResponse
	ServiceGroup
	Command
	Attribute
	StaticAttribute
	Lazy
	DeleteServiceGroupRequest
	CreateServiceGroupRequest
	ListServiceGroupsResponse
	UpdateServiceGroupRequest
	ServiceGroupResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type IotAgent struct {
	Host        string `protobuf:"bytes,1,opt,name=Host,json=host,omitempty" json:"Host,omitempty"`
	Protocol    string `protobuf:"bytes,2,opt,name=Protocol,json=protocol,omitempty" json:"Protocol,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,json=description, omitempty" json:"Description,omitempty"`
	Resource    string `protobuf:"bytes,4,opt,name=Resource,json=resource, omitempty" json:"Resource,omitempty"`
}

func (m *IotAgent) Reset()                    { *m = IotAgent{} }
func (m *IotAgent) String() string            { return proto1.CompactTextString(m) }
func (*IotAgent) ProtoMessage()               {}
func (*IotAgent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IotAgent) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *IotAgent) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *IotAgent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *IotAgent) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type AddIotAgentRequest struct {
	IotAgent *IotAgent `protobuf:"bytes,1,opt,name=iotAgent" json:"iotAgent,omitempty"`
}

func (m *AddIotAgentRequest) Reset()                    { *m = AddIotAgentRequest{} }
func (m *AddIotAgentRequest) String() string            { return proto1.CompactTextString(m) }
func (*AddIotAgentRequest) ProtoMessage()               {}
func (*AddIotAgentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddIotAgentRequest) GetIotAgent() *IotAgent {
	if m != nil {
		return m.IotAgent
	}
	return nil
}

type ListIotAgentsResponse struct {
	IotAgent []*IotAgent `protobuf:"bytes,1,rep,name=iotAgent" json:"iotAgent,omitempty"`
}

func (m *ListIotAgentsResponse) Reset()                    { *m = ListIotAgentsResponse{} }
func (m *ListIotAgentsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListIotAgentsResponse) ProtoMessage()               {}
func (*ListIotAgentsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListIotAgentsResponse) GetIotAgent() []*IotAgent {
	if m != nil {
		return m.IotAgent
	}
	return nil
}

type GetIotAgentWithProtocolRequest struct {
	Protocol *google_protobuf2.StringValue `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
}

func (m *GetIotAgentWithProtocolRequest) Reset()                    { *m = GetIotAgentWithProtocolRequest{} }
func (m *GetIotAgentWithProtocolRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetIotAgentWithProtocolRequest) ProtoMessage()               {}
func (*GetIotAgentWithProtocolRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetIotAgentWithProtocolRequest) GetProtocol() *google_protobuf2.StringValue {
	if m != nil {
		return m.Protocol
	}
	return nil
}

type GetIotAgentWithProtocolResponse struct {
	IotAgent []*IotAgent `protobuf:"bytes,1,rep,name=iotAgent" json:"iotAgent,omitempty"`
}

func (m *GetIotAgentWithProtocolResponse) Reset()                    { *m = GetIotAgentWithProtocolResponse{} }
func (m *GetIotAgentWithProtocolResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetIotAgentWithProtocolResponse) ProtoMessage()               {}
func (*GetIotAgentWithProtocolResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetIotAgentWithProtocolResponse) GetIotAgent() []*IotAgent {
	if m != nil {
		return m.IotAgent
	}
	return nil
}

func init() {
	proto1.RegisterType((*IotAgent)(nil), "proto.IotAgent")
	proto1.RegisterType((*AddIotAgentRequest)(nil), "proto.AddIotAgentRequest")
	proto1.RegisterType((*ListIotAgentsResponse)(nil), "proto.ListIotAgentsResponse")
	proto1.RegisterType((*GetIotAgentWithProtocolRequest)(nil), "proto.GetIotAgentWithProtocolRequest")
	proto1.RegisterType((*GetIotAgentWithProtocolResponse)(nil), "proto.GetIotAgentWithProtocolResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IotAgentService service

type IotAgentServiceClient interface {
	AddIotAgent(ctx context.Context, in *AddIotAgentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ListIotAgents(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListIotAgentsResponse, error)
	GetIotAgentWithProtocol(ctx context.Context, in *GetIotAgentWithProtocolRequest, opts ...grpc.CallOption) (*GetIotAgentWithProtocolResponse, error)
}

type iotAgentServiceClient struct {
	cc *grpc.ClientConn
}

func NewIotAgentServiceClient(cc *grpc.ClientConn) IotAgentServiceClient {
	return &iotAgentServiceClient{cc}
}

func (c *iotAgentServiceClient) AddIotAgent(ctx context.Context, in *AddIotAgentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.IotAgentService/AddIotAgent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotAgentServiceClient) ListIotAgents(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListIotAgentsResponse, error) {
	out := new(ListIotAgentsResponse)
	err := grpc.Invoke(ctx, "/proto.IotAgentService/ListIotAgents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotAgentServiceClient) GetIotAgentWithProtocol(ctx context.Context, in *GetIotAgentWithProtocolRequest, opts ...grpc.CallOption) (*GetIotAgentWithProtocolResponse, error) {
	out := new(GetIotAgentWithProtocolResponse)
	err := grpc.Invoke(ctx, "/proto.IotAgentService/GetIotAgentWithProtocol", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IotAgentService service

type IotAgentServiceServer interface {
	AddIotAgent(context.Context, *AddIotAgentRequest) (*google_protobuf1.Empty, error)
	ListIotAgents(context.Context, *google_protobuf1.Empty) (*ListIotAgentsResponse, error)
	GetIotAgentWithProtocol(context.Context, *GetIotAgentWithProtocolRequest) (*GetIotAgentWithProtocolResponse, error)
}

func RegisterIotAgentServiceServer(s *grpc.Server, srv IotAgentServiceServer) {
	s.RegisterService(&_IotAgentService_serviceDesc, srv)
}

func _IotAgentService_AddIotAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIotAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotAgentServiceServer).AddIotAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotAgentService/AddIotAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotAgentServiceServer).AddIotAgent(ctx, req.(*AddIotAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotAgentService_ListIotAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotAgentServiceServer).ListIotAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotAgentService/ListIotAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotAgentServiceServer).ListIotAgents(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotAgentService_GetIotAgentWithProtocol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIotAgentWithProtocolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotAgentServiceServer).GetIotAgentWithProtocol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotAgentService/GetIotAgentWithProtocol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotAgentServiceServer).GetIotAgentWithProtocol(ctx, req.(*GetIotAgentWithProtocolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IotAgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IotAgentService",
	HandlerType: (*IotAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddIotAgent",
			Handler:    _IotAgentService_AddIotAgent_Handler,
		},
		{
			MethodName: "ListIotAgents",
			Handler:    _IotAgentService_ListIotAgents_Handler,
		},
		{
			MethodName: "GetIotAgentWithProtocol",
			Handler:    _IotAgentService_GetIotAgentWithProtocol_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iotAgents.proto",
}

func init() { proto1.RegisterFile("iotAgents.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x6f, 0x4b, 0x2a, 0x41,
	0x14, 0xc6, 0xfd, 0x77, 0x2f, 0x7b, 0x8f, 0xdc, 0x2b, 0xcc, 0x25, 0xdb, 0xb6, 0xc5, 0x64, 0xc9,
	0x08, 0x94, 0x15, 0xec, 0x4d, 0x6f, 0x0d, 0xc3, 0x82, 0x88, 0x58, 0xa1, 0xa0, 0x77, 0xeb, 0x3a,
	0xad, 0x13, 0xba, 0x33, 0xcd, 0xcc, 0x16, 0x7d, 0x85, 0x3e, 0x46, 0x9f, 0x34, 0x1c, 0x67, 0x56,
	0xd3, 0x34, 0xe8, 0xd5, 0x70, 0xe6, 0xfc, 0xce, 0x33, 0xcf, 0x3c, 0x07, 0x2a, 0x84, 0xca, 0x6e,
	0x8c, 0x13, 0x29, 0x7c, 0xc6, 0xa9, 0xa4, 0xe8, 0x97, 0x3a, 0x1c, 0x37, 0xa6, 0x34, 0x9e, 0xe0,
	0x76, 0xc8, 0x48, 0x3b, 0x4c, 0x12, 0x2a, 0x43, 0x49, 0x68, 0xa2, 0x21, 0x67, 0x5f, 0x77, 0x55,
	0x35, 0x4c, 0x1f, 0xda, 0x78, 0xca, 0xe4, 0xab, 0x6e, 0xd6, 0x56, 0x9b, 0x2f, 0x3c, 0x64, 0x0c,
	0x73, 0x3d, 0xec, 0xbd, 0xe7, 0xc1, 0xba, 0xd4, 0xaf, 0x22, 0x17, 0x4a, 0x17, 0x54, 0x48, 0x3b,
	0x5f, 0xcf, 0x1f, 0xff, 0x09, 0xfe, 0x8d, 0xa9, 0x90, 0x2d, 0x3a, 0x25, 0x52, 0x09, 0xa2, 0x43,
	0xb0, 0x6e, 0x66, 0x33, 0x11, 0x9d, 0xd8, 0x05, 0x45, 0x20, 0xa6, 0xeb, 0x25, 0xaa, 0x09, 0xe5,
	0x1e, 0x16, 0x11, 0x27, 0x6c, 0xe6, 0xd1, 0x2e, 0x2a, 0xb0, 0x3a, 0x5a, 0x5c, 0xb5, 0xea, 0x0b,
	0xb8, 0x01, 0x56, 0x80, 0x05, 0x4d, 0x79, 0x84, 0xed, 0x92, 0x22, 0xff, 0x73, 0x5d, 0x2f, 0x61,
	0x5e, 0x17, 0x50, 0x77, 0x34, 0x32, 0x36, 0x03, 0xfc, 0x94, 0x62, 0x21, 0x51, 0x13, 0x2c, 0x93,
	0x97, 0x72, 0x5c, 0xee, 0x54, 0xe6, 0x9f, 0xf2, 0x33, 0x32, 0x03, 0xbc, 0x1e, 0xec, 0x5c, 0x11,
	0x21, 0x4d, 0x47, 0x04, 0x58, 0x30, 0x9a, 0x08, 0xbc, 0xa2, 0x52, 0xdc, 0xae, 0x72, 0x0f, 0xb5,
	0x3e, 0xce, 0x44, 0xee, 0x88, 0x1c, 0x9b, 0x44, 0x8c, 0xa9, 0x53, 0xb0, 0x4c, 0x28, 0xda, 0x94,
	0xeb, 0xcf, 0x57, 0xe0, 0x9b, 0x15, 0xf8, 0x03, 0xc9, 0x49, 0x12, 0xdf, 0x86, 0x93, 0x14, 0x07,
	0x19, 0xed, 0x5d, 0xc3, 0xc1, 0x46, 0xed, 0x1f, 0x78, 0xed, 0xbc, 0x15, 0xa0, 0x62, 0xae, 0x07,
	0x98, 0x3f, 0x93, 0x08, 0xa3, 0x33, 0x28, 0x2f, 0x05, 0x89, 0xf6, 0xf4, 0xf4, 0x7a, 0xb8, 0x4e,
	0x75, 0xcd, 0xf5, 0xb9, 0x5a, 0x45, 0x0e, 0xf5, 0xe1, 0xef, 0xa7, 0x24, 0xd1, 0x06, 0xd4, 0x71,
	0xb5, 0xfa, 0x97, 0xb9, 0x7b, 0x39, 0xf4, 0x08, 0xbb, 0x1b, 0x3e, 0x8c, 0x1a, 0x7a, 0x74, 0x7b,
	0xd8, 0xce, 0xd1, 0x77, 0x98, 0x79, 0x6b, 0xf8, 0x5b, 0x81, 0x27, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0x1c, 0x8e, 0x7b, 0x62, 0x03, 0x00, 0x00,
}
