// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iotDevice.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	iotDevice.proto

It has these top-level messages:
	Attributes
	Lazy
	StaticAttributes
	Commands
	IotDevice
	DeleteIotDeviceRequest
	CreateIotDeviceRequest
	ListIotDevicesResponse
	UpdateIotDeviceRequest
	IotDeviceResponse
	IotDeviceRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Attributes struct {
	ObjectId string `protobuf:"bytes,1,opt,name=ObjectId,json=object_id,omitempty" json:"ObjectId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,json=name,omitempty" json:"Name,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=Type,json=type,omitempty" json:"Type,omitempty"`
}

func (m *Attributes) Reset()                    { *m = Attributes{} }
func (m *Attributes) String() string            { return proto1.CompactTextString(m) }
func (*Attributes) ProtoMessage()               {}
func (*Attributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Attributes) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Attributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attributes) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Lazy struct {
	ObjectId string `protobuf:"bytes,3,opt,name=ObjectId,json=object_id,omitempty" json:"ObjectId,omitempty"`
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name,omitempty" json:"Name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=Type,json=type,omitempty" json:"Type,omitempty"`
}

func (m *Lazy) Reset()                    { *m = Lazy{} }
func (m *Lazy) String() string            { return proto1.CompactTextString(m) }
func (*Lazy) ProtoMessage()               {}
func (*Lazy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Lazy) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Lazy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lazy) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type StaticAttributes struct {
	Name  string `protobuf:"bytes,3,opt,name=Name,json=name,omitempty" json:"Name,omitempty"`
	Value string `protobuf:"bytes,1,opt,name=Value,json=value,omitempty" json:"Value,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=Type,json=type,omitempty" json:"Type,omitempty"`
}

func (m *StaticAttributes) Reset()                    { *m = StaticAttributes{} }
func (m *StaticAttributes) String() string            { return proto1.CompactTextString(m) }
func (*StaticAttributes) ProtoMessage()               {}
func (*StaticAttributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StaticAttributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StaticAttributes) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StaticAttributes) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Commands struct {
	ObjectId string `protobuf:"bytes,3,opt,name=ObjectId,json=object_id,omitempty" json:"ObjectId,omitempty"`
	Name     string `protobuf:"bytes,1,opt,name=Name,json=name,omitempty" json:"Name,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=Type,json=type,omitempty" json:"Type,omitempty"`
}

func (m *Commands) Reset()                    { *m = Commands{} }
func (m *Commands) String() string            { return proto1.CompactTextString(m) }
func (*Commands) ProtoMessage()               {}
func (*Commands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Commands) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Commands) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Commands) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type IotDevice struct {
	DeviceId         string              `protobuf:"bytes,10,opt,name=DeviceId,json=device_id,omitempty" json:"DeviceId,omitempty"`
	Service          string              `protobuf:"bytes,1,opt,name=Service,json=service,omitempty" json:"Service,omitempty"`
	ServicePath      string              `protobuf:"bytes,2,opt,name=ServicePath,json=service_path,omitempty" json:"ServicePath,omitempty"`
	EntityName       string              `protobuf:"bytes,3,opt,name=EntityName,json=entity_name,omitempty" json:"EntityName,omitempty"`
	EntityType       string              `protobuf:"bytes,4,opt,name=EntityType,json=entity_type,omitempty" json:"EntityType,omitempty"`
	Attributes       []*Attributes       `protobuf:"bytes,5,rep,name=attributes,json=attributes,omitempty" json:"attributes,omitempty"`
	Lazy             []*Lazy             `protobuf:"bytes,6,rep,name=lazy,json=lazy,omitempty" json:"lazy,omitempty"`
	Commands         []*Commands         `protobuf:"bytes,7,rep,name=commands,json=commands,omitempty" json:"commands,omitempty"`
	StaticAttributes []*StaticAttributes `protobuf:"bytes,8,rep,name=static_attributes,json=static_attributes,omitempty" json:"static_attributes,omitempty"`
	Protocol         string              `protobuf:"bytes,9,opt,name=Protocol" json:"Protocol,omitempty"`
}

func (m *IotDevice) Reset()                    { *m = IotDevice{} }
func (m *IotDevice) String() string            { return proto1.CompactTextString(m) }
func (*IotDevice) ProtoMessage()               {}
func (*IotDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IotDevice) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *IotDevice) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *IotDevice) GetServicePath() string {
	if m != nil {
		return m.ServicePath
	}
	return ""
}

func (m *IotDevice) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

func (m *IotDevice) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *IotDevice) GetAttributes() []*Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *IotDevice) GetLazy() []*Lazy {
	if m != nil {
		return m.Lazy
	}
	return nil
}

func (m *IotDevice) GetCommands() []*Commands {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *IotDevice) GetStaticAttributes() []*StaticAttributes {
	if m != nil {
		return m.StaticAttributes
	}
	return nil
}

func (m *IotDevice) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type DeleteIotDeviceRequest struct {
	Id string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *DeleteIotDeviceRequest) Reset()                    { *m = DeleteIotDeviceRequest{} }
func (m *DeleteIotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteIotDeviceRequest) ProtoMessage()               {}
func (*DeleteIotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteIotDeviceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateIotDeviceRequest struct {
	IotDevice *IotDevice `protobuf:"bytes,1,opt,name=IotDevice" json:"IotDevice,omitempty"`
}

func (m *CreateIotDeviceRequest) Reset()                    { *m = CreateIotDeviceRequest{} }
func (m *CreateIotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateIotDeviceRequest) ProtoMessage()               {}
func (*CreateIotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateIotDeviceRequest) GetIotDevice() *IotDevice {
	if m != nil {
		return m.IotDevice
	}
	return nil
}

type ListIotDevicesResponse struct {
	IotDevices []*IotDevice `protobuf:"bytes,1,rep,name=IotDevices" json:"IotDevices,omitempty"`
}

func (m *ListIotDevicesResponse) Reset()                    { *m = ListIotDevicesResponse{} }
func (m *ListIotDevicesResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListIotDevicesResponse) ProtoMessage()               {}
func (*ListIotDevicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListIotDevicesResponse) GetIotDevices() []*IotDevice {
	if m != nil {
		return m.IotDevices
	}
	return nil
}

type UpdateIotDeviceRequest struct {
	IotDevice *IotDevice `protobuf:"bytes,1,opt,name=IotDevice" json:"IotDevice,omitempty"`
}

func (m *UpdateIotDeviceRequest) Reset()                    { *m = UpdateIotDeviceRequest{} }
func (m *UpdateIotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateIotDeviceRequest) ProtoMessage()               {}
func (*UpdateIotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateIotDeviceRequest) GetIotDevice() *IotDevice {
	if m != nil {
		return m.IotDevice
	}
	return nil
}

type IotDeviceResponse struct {
	IotDevice *IotDevice `protobuf:"bytes,1,opt,name=IotDevice" json:"IotDevice,omitempty"`
}

func (m *IotDeviceResponse) Reset()                    { *m = IotDeviceResponse{} }
func (m *IotDeviceResponse) String() string            { return proto1.CompactTextString(m) }
func (*IotDeviceResponse) ProtoMessage()               {}
func (*IotDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *IotDeviceResponse) GetIotDevice() *IotDevice {
	if m != nil {
		return m.IotDevice
	}
	return nil
}

type IotDeviceRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *IotDeviceRequest) Reset()                    { *m = IotDeviceRequest{} }
func (m *IotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*IotDeviceRequest) ProtoMessage()               {}
func (*IotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IotDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto1.RegisterType((*Attributes)(nil), "proto.Attributes")
	proto1.RegisterType((*Lazy)(nil), "proto.Lazy")
	proto1.RegisterType((*StaticAttributes)(nil), "proto.StaticAttributes")
	proto1.RegisterType((*Commands)(nil), "proto.Commands")
	proto1.RegisterType((*IotDevice)(nil), "proto.IotDevice")
	proto1.RegisterType((*DeleteIotDeviceRequest)(nil), "proto.DeleteIotDeviceRequest")
	proto1.RegisterType((*CreateIotDeviceRequest)(nil), "proto.CreateIotDeviceRequest")
	proto1.RegisterType((*ListIotDevicesResponse)(nil), "proto.ListIotDevicesResponse")
	proto1.RegisterType((*UpdateIotDeviceRequest)(nil), "proto.UpdateIotDeviceRequest")
	proto1.RegisterType((*IotDeviceResponse)(nil), "proto.IotDeviceResponse")
	proto1.RegisterType((*IotDeviceRequest)(nil), "proto.IotDeviceRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IotDevicesService service

type IotDevicesServiceClient interface {
	DeleteIotDevice(ctx context.Context, in *DeleteIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	CreateIotDevice(ctx context.Context, in *CreateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ListIotDevices(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListIotDevicesResponse, error)
	UpdateIotDevice(ctx context.Context, in *UpdateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	IotDevice(ctx context.Context, in *IotDeviceRequest, opts ...grpc.CallOption) (*IotDeviceResponse, error)
}

type iotDevicesServiceClient struct {
	cc *grpc.ClientConn
}

func NewIotDevicesServiceClient(cc *grpc.ClientConn) IotDevicesServiceClient {
	return &iotDevicesServiceClient{cc}
}

func (c *iotDevicesServiceClient) DeleteIotDevice(ctx context.Context, in *DeleteIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/DeleteIotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) CreateIotDevice(ctx context.Context, in *CreateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/CreateIotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) ListIotDevices(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListIotDevicesResponse, error) {
	out := new(ListIotDevicesResponse)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/ListIotDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) UpdateIotDevice(ctx context.Context, in *UpdateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/UpdateIotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) IotDevice(ctx context.Context, in *IotDeviceRequest, opts ...grpc.CallOption) (*IotDeviceResponse, error) {
	out := new(IotDeviceResponse)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/IotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IotDevicesService service

type IotDevicesServiceServer interface {
	DeleteIotDevice(context.Context, *DeleteIotDeviceRequest) (*google_protobuf1.Empty, error)
	CreateIotDevice(context.Context, *CreateIotDeviceRequest) (*google_protobuf1.Empty, error)
	ListIotDevices(context.Context, *google_protobuf1.Empty) (*ListIotDevicesResponse, error)
	UpdateIotDevice(context.Context, *UpdateIotDeviceRequest) (*google_protobuf1.Empty, error)
	IotDevice(context.Context, *IotDeviceRequest) (*IotDeviceResponse, error)
}

func RegisterIotDevicesServiceServer(s *grpc.Server, srv IotDevicesServiceServer) {
	s.RegisterService(&_IotDevicesService_serviceDesc, srv)
}

func _IotDevicesService_DeleteIotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).DeleteIotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/DeleteIotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).DeleteIotDevice(ctx, req.(*DeleteIotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_CreateIotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).CreateIotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/CreateIotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).CreateIotDevice(ctx, req.(*CreateIotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_ListIotDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).ListIotDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/ListIotDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).ListIotDevices(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_UpdateIotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).UpdateIotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/UpdateIotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).UpdateIotDevice(ctx, req.(*UpdateIotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_IotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).IotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/IotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).IotDevice(ctx, req.(*IotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IotDevicesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IotDevicesService",
	HandlerType: (*IotDevicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteIotDevice",
			Handler:    _IotDevicesService_DeleteIotDevice_Handler,
		},
		{
			MethodName: "CreateIotDevice",
			Handler:    _IotDevicesService_CreateIotDevice_Handler,
		},
		{
			MethodName: "ListIotDevices",
			Handler:    _IotDevicesService_ListIotDevices_Handler,
		},
		{
			MethodName: "UpdateIotDevice",
			Handler:    _IotDevicesService_UpdateIotDevice_Handler,
		},
		{
			MethodName: "IotDevice",
			Handler:    _IotDevicesService_IotDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iotDevice.proto",
}

func init() { proto1.RegisterFile("iotDevice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0xb5, 0x69, 0xb7, 0xf6, 0x56, 0xea, 0x1f, 0xff, 0xa0, 0xb3, 0xba, 0x81, 0xa6, 0x48,
	0x48, 0x45, 0xa0, 0x14, 0x15, 0xf1, 0xc4, 0x0b, 0xa8, 0x9d, 0x44, 0xa7, 0x89, 0x4d, 0x19, 0xf0,
	0x5a, 0xb9, 0x8d, 0xd9, 0x8c, 0x9a, 0x38, 0xd4, 0xee, 0xa4, 0xec, 0x99, 0xaf, 0xca, 0xf7, 0x40,
	0x71, 0x9c, 0xd4, 0x49, 0x43, 0x01, 0x09, 0xf1, 0xd4, 0x5e, 0xdf, 0x73, 0xee, 0xb9, 0xd7, 0xe7,
	0xc6, 0xd0, 0x61, 0x5c, 0x4e, 0xe9, 0x1d, 0x5b, 0x52, 0x27, 0x5c, 0x73, 0xc9, 0x51, 0x5d, 0xfd,
	0x0c, 0x4e, 0x6e, 0x38, 0xbf, 0x59, 0xd1, 0x11, 0x09, 0xd9, 0x88, 0x04, 0x01, 0x97, 0x44, 0x32,
	0x1e, 0x88, 0x04, 0x34, 0x38, 0xd6, 0x59, 0x15, 0x2d, 0x36, 0x9f, 0x47, 0xd4, 0x0f, 0x65, 0x94,
	0x24, 0x6d, 0x0e, 0xf0, 0x56, 0xca, 0x35, 0x5b, 0x6c, 0x24, 0x15, 0xe8, 0x09, 0x34, 0x2e, 0x17,
	0x5f, 0xe8, 0x52, 0xce, 0x3c, 0x5c, 0x39, 0xad, 0x0c, 0x9b, 0xee, 0xff, 0x5c, 0xc5, 0x73, 0xe6,
	0x3d, 0xe7, 0x3e, 0x93, 0x8a, 0x8a, 0x4e, 0xa0, 0xf6, 0x9e, 0xf8, 0x14, 0x57, 0x15, 0xa4, 0x1d,
	0x10, 0x9f, 0xe6, 0xb3, 0x1f, 0xa2, 0x90, 0x62, 0x2b, 0xc9, 0xca, 0x28, 0x34, 0xb2, 0x36, 0x83,
	0xda, 0x05, 0xb9, 0x8f, 0x72, 0x52, 0xd6, 0xaf, 0xa5, 0x2a, 0x7b, 0xa5, 0xaa, 0xa5, 0x52, 0x01,
	0x74, 0xaf, 0xe3, 0xab, 0x58, 0x1a, 0x13, 0xa6, 0xf5, 0xac, 0xd2, 0x7a, 0x8f, 0xa1, 0xfe, 0x89,
	0xac, 0x36, 0xa9, 0x5c, 0xe7, 0x2e, 0x0e, 0x7e, 0x5b, 0xcf, 0x87, 0xc6, 0x84, 0xfb, 0x3e, 0x09,
	0x3c, 0xf1, 0x2f, 0xc6, 0xfb, 0x6e, 0x41, 0x73, 0x96, 0x2e, 0x44, 0x2c, 0x98, 0xfc, 0x9b, 0x79,
	0x18, 0x12, 0x41, 0x4f, 0xc5, 0x79, 0x41, 0x1b, 0x0e, 0xaf, 0xe9, 0x3a, 0x3e, 0xd7, 0x9a, 0x3d,
	0x91, 0x84, 0x06, 0xe6, 0x19, 0xb4, 0x34, 0xe6, 0x8a, 0xc8, 0x5b, 0xad, 0xde, 0xd7, 0xb8, 0x79,
	0x48, 0xe4, 0xad, 0x01, 0x7e, 0x0a, 0x70, 0x16, 0x48, 0x26, 0x23, 0xe3, 0x5a, 0x1f, 0x52, 0x75,
	0x32, 0x2f, 0x8c, 0x93, 0x41, 0xd5, 0x50, 0xb5, 0x1c, 0x34, 0x3f, 0x1b, 0x7a, 0x0d, 0x40, 0x32,
	0xd3, 0x70, 0xfd, 0xd4, 0x1a, 0xb6, 0xc6, 0xbd, 0x64, 0x65, 0x9d, 0xad, 0x9b, 0xee, 0x83, 0x2d,
	0x28, 0xa7, 0x53, 0x5b, 0x91, 0xfb, 0x08, 0x1f, 0x28, 0x5a, 0x4b, 0xd3, 0xe2, 0xad, 0x73, 0xdb,
	0x71, 0xc2, 0x80, 0xbe, 0x82, 0xc6, 0x52, 0x5b, 0x86, 0x0f, 0x15, 0xbc, 0xa3, 0xe1, 0xa9, 0x93,
	0x2e, 0x4a, 0x01, 0x06, 0xed, 0x12, 0x7a, 0x42, 0x6d, 0xd6, 0xdc, 0xe8, 0xb2, 0xa1, 0xf8, 0x47,
	0x9a, 0x5f, 0xdc, 0x3c, 0xf7, 0x78, 0x87, 0x61, 0x14, 0x1c, 0x40, 0xe3, 0x2a, 0xa6, 0x2d, 0xf9,
	0x0a, 0x37, 0xd5, 0xc5, 0x64, 0xb1, 0x3d, 0x84, 0xfe, 0x94, 0xae, 0xa8, 0xa4, 0x99, 0xd9, 0x2e,
	0xfd, 0xba, 0xa1, 0x42, 0xa2, 0x36, 0x54, 0xb3, 0x0f, 0xb5, 0x3a, 0xf3, 0xec, 0x77, 0xd0, 0x9f,
	0xac, 0x29, 0x29, 0x41, 0x3a, 0xc6, 0xaa, 0x28, 0x42, 0x6b, 0xdc, 0xd5, 0x8d, 0x6e, 0xb1, 0x5b,
	0x88, 0x7d, 0x0e, 0xfd, 0x0b, 0x26, 0x64, 0x76, 0x20, 0x5c, 0x2a, 0x42, 0x1e, 0x08, 0x8a, 0x5e,
	0x00, 0x6c, 0x4f, 0x71, 0x45, 0xcd, 0xbc, 0x5b, 0xca, 0xc0, 0xc4, 0x5d, 0x7d, 0x0c, 0xbd, 0xbf,
	0xd1, 0xd5, 0x04, 0x7a, 0x46, 0x0d, 0xdd, 0xd0, 0x9f, 0x16, 0xb1, 0xa1, 0x5b, 0x7a, 0x91, 0xd3,
	0xec, 0x22, 0xa7, 0xe3, 0x6f, 0x96, 0xa1, 0x24, 0xf4, 0xc7, 0x80, 0xce, 0xa1, 0x53, 0x30, 0x02,
	0x3d, 0xd2, 0x4a, 0xe5, 0x06, 0x0d, 0xfa, 0x4e, 0xf2, 0xf6, 0x3a, 0xe9, 0xdb, 0xeb, 0x9c, 0xa9,
	0x4f, 0xf7, 0xbf, 0xb8, 0x56, 0xc1, 0xaa, 0xac, 0x56, 0xb9, 0x85, 0x7b, 0x6a, 0xcd, 0xa0, 0x9d,
	0x37, 0x0b, 0xfd, 0x04, 0x3b, 0x48, 0x25, 0xca, 0xbd, 0x4d, 0xda, 0x2a, 0x78, 0x95, 0xb5, 0x55,
	0xee, 0xe1, 0x9e, 0xb6, 0xde, 0x98, 0xcf, 0xd3, 0xd1, 0x8e, 0x25, 0x9a, 0x8f, 0x77, 0x13, 0x69,
	0x37, 0x8b, 0x03, 0x95, 0x7a, 0xf9, 0x23, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xb7, 0x95, 0x3f, 0xf8,
	0x06, 0x00, 0x00,
}
