// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iotDevice.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Attributes struct {
	// @inject_tag: json:"object_id,omitempty" bson:"object_id"
	ObjectId string `protobuf:"bytes,1,opt,name=ObjectId,json=object_id,omitempty" json:"object_id,omitempty" bson:"object_id"`
	// @inject_tag: json:"name,omitempty" bson:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,json=name,omitempty" json:"name,omitempty" bson:"name"`
	// @inject_tag: json:"type,omitempty" bson:"type"
	Type string `protobuf:"bytes,3,opt,name=Type,json=type,omitempty" json:"type,omitempty" bson:"type"`
}

func (m *Attributes) Reset()                    { *m = Attributes{} }
func (m *Attributes) String() string            { return proto1.CompactTextString(m) }
func (*Attributes) ProtoMessage()               {}
func (*Attributes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Attributes) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Attributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attributes) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type StaticAttributes struct {
	// @inject_tag: json:"name,omitempty" bson:"name"
	Name string `protobuf:"bytes,3,opt,name=Name,json=name,omitempty" json:"name,omitempty" bson:"name"`
	// @inject_tag: json:"value,omitempty" bson:"value"
	Value string `protobuf:"bytes,1,opt,name=Value,json=value,omitempty" json:"value,omitempty" bson:"value"`
	// @inject_tag: json:"type,omitempty" bson:"type"
	Type string `protobuf:"bytes,2,opt,name=Type,json=type,omitempty" json:"type,omitempty" bson:"type"`
}

func (m *StaticAttributes) Reset()                    { *m = StaticAttributes{} }
func (m *StaticAttributes) String() string            { return proto1.CompactTextString(m) }
func (*StaticAttributes) ProtoMessage()               {}
func (*StaticAttributes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *StaticAttributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StaticAttributes) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StaticAttributes) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Commands struct {
	// @inject_tag: json:"object_id,omitempty" bson:"object_id"
	ObjectId string `protobuf:"bytes,3,opt,name=ObjectId,json=object_id,omitempty" json:"object_id,omitempty" bson:"object_id"`
	// @inject_tag: json:"name,omitempty" bson:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,json=name,omitempty" json:"name,omitempty" bson:"name"`
	// @inject_tag: json:"type,omitempty" bson:"type"
	Type string `protobuf:"bytes,2,opt,name=Type,json=type,omitempty" json:"type,omitempty" bson:"type"`
}

func (m *Commands) Reset()                    { *m = Commands{} }
func (m *Commands) String() string            { return proto1.CompactTextString(m) }
func (*Commands) ProtoMessage()               {}
func (*Commands) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Commands) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Commands) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Commands) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type IotDevice struct {
	// @inject_tag: json:"device_id,omitempty" bson:"device_id"
	DeviceId string `protobuf:"bytes,10,opt,name=DeviceId,json=device_id,omitempty" json:"device_id,omitempty" bson:"device_id"`
	// @inject_tag: json:"service,omitempty" bson:"service"
	Service string `protobuf:"bytes,1,opt,name=Service,json=service,omitempty" json:"service,omitempty" bson:"service"`
	// @inject_tag: json:"service_path,omitempty" bson:"service_path"
	ServicePath string `protobuf:"bytes,2,opt,name=ServicePath,json=service_path,omitempty" json:"service_path,omitempty" bson:"service_path"`
	// @inject_tag: json:"entity_name,omitempty" bson:"entity_name"
	EntityName string `protobuf:"bytes,3,opt,name=EntityName,json=entity_name,omitempty" json:"entity_name,omitempty" bson:"entity_name"`
	// @inject_tag: json:"entity_type,omitempty" bson:"entity_type"
	EntityType string `protobuf:"bytes,4,opt,name=EntityType,json=entity_type,omitempty" json:"entity_type,omitempty" bson:"entity_type"`
	// @inject_tag: json:"attributes,omitempty" bson:"attributes"
	Attributes []*Attributes `protobuf:"bytes,5,rep,name=attributes,json=attributes,omitempty" json:"attributes,omitempty" bson:"attributes"`
	// @inject_tag: json:"lazy,omitempty" bson:"lazy"
	Lazy []*Lazy `protobuf:"bytes,6,rep,name=lazy,json=lazy,omitempty" json:"lazy,omitempty" bson:"lazy"`
	// @inject_tag: json:"commands,omitempty" bson:"commands"
	Commands []*Commands `protobuf:"bytes,7,rep,name=commands,json=commands,omitempty" json:"commands,omitempty" bson:"commands"`
	// @inject_tag: json:"static_attributes,omitempty" bson:"static_attributes"
	StaticAttributes []*StaticAttributes `protobuf:"bytes,8,rep,name=static_attributes,json=static_attributes,omitempty" json:"static_attributes,omitempty" bson:"static_attributes"`
	// @inject_tag: json:"protocol,omitempty" bson:"protocol"
	Protocol string `protobuf:"bytes,9,opt,name=Protocol" json:"protocol,omitempty" bson:"protocol"`
}

func (m *IotDevice) Reset()                    { *m = IotDevice{} }
func (m *IotDevice) String() string            { return proto1.CompactTextString(m) }
func (*IotDevice) ProtoMessage()               {}
func (*IotDevice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *IotDevice) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *IotDevice) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *IotDevice) GetServicePath() string {
	if m != nil {
		return m.ServicePath
	}
	return ""
}

func (m *IotDevice) GetEntityName() string {
	if m != nil {
		return m.EntityName
	}
	return ""
}

func (m *IotDevice) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *IotDevice) GetAttributes() []*Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *IotDevice) GetLazy() []*Lazy {
	if m != nil {
		return m.Lazy
	}
	return nil
}

func (m *IotDevice) GetCommands() []*Commands {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *IotDevice) GetStaticAttributes() []*StaticAttributes {
	if m != nil {
		return m.StaticAttributes
	}
	return nil
}

func (m *IotDevice) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type DeleteIotDeviceRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Protocol string `protobuf:"bytes,2,opt,name=Protocol" json:"Protocol,omitempty"`
}

func (m *DeleteIotDeviceRequest) Reset()                    { *m = DeleteIotDeviceRequest{} }
func (m *DeleteIotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteIotDeviceRequest) ProtoMessage()               {}
func (*DeleteIotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *DeleteIotDeviceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteIotDeviceRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type CreateIotDeviceRequest struct {
	IotDevice *IotDevice `protobuf:"bytes,1,opt,name=IotDevice" json:"IotDevice,omitempty"`
}

func (m *CreateIotDeviceRequest) Reset()                    { *m = CreateIotDeviceRequest{} }
func (m *CreateIotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateIotDeviceRequest) ProtoMessage()               {}
func (*CreateIotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *CreateIotDeviceRequest) GetIotDevice() *IotDevice {
	if m != nil {
		return m.IotDevice
	}
	return nil
}

type ListIotDevicesResponse struct {
	IotDevices []*IotDevice `protobuf:"bytes,1,rep,name=IotDevices" json:"IotDevices,omitempty"`
}

func (m *ListIotDevicesResponse) Reset()                    { *m = ListIotDevicesResponse{} }
func (m *ListIotDevicesResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListIotDevicesResponse) ProtoMessage()               {}
func (*ListIotDevicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *ListIotDevicesResponse) GetIotDevices() []*IotDevice {
	if m != nil {
		return m.IotDevices
	}
	return nil
}

type UpdateIotDeviceRequest struct {
	IotDevice *IotDevice `protobuf:"bytes,1,opt,name=IotDevice" json:"IotDevice,omitempty"`
}

func (m *UpdateIotDeviceRequest) Reset()                    { *m = UpdateIotDeviceRequest{} }
func (m *UpdateIotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateIotDeviceRequest) ProtoMessage()               {}
func (*UpdateIotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *UpdateIotDeviceRequest) GetIotDevice() *IotDevice {
	if m != nil {
		return m.IotDevice
	}
	return nil
}

type IotDeviceResponse struct {
	IotDevice *IotDevice `protobuf:"bytes,1,opt,name=IotDevice" json:"IotDevice,omitempty"`
}

func (m *IotDeviceResponse) Reset()                    { *m = IotDeviceResponse{} }
func (m *IotDeviceResponse) String() string            { return proto1.CompactTextString(m) }
func (*IotDeviceResponse) ProtoMessage()               {}
func (*IotDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *IotDeviceResponse) GetIotDevice() *IotDevice {
	if m != nil {
		return m.IotDevice
	}
	return nil
}

type IotDeviceRequest struct {
	ID       string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Protocol string `protobuf:"bytes,2,opt,name=Protocol" json:"Protocol,omitempty"`
}

func (m *IotDeviceRequest) Reset()                    { *m = IotDeviceRequest{} }
func (m *IotDeviceRequest) String() string            { return proto1.CompactTextString(m) }
func (*IotDeviceRequest) ProtoMessage()               {}
func (*IotDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *IotDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *IotDeviceRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func init() {
	proto1.RegisterType((*Attributes)(nil), "proto.Attributes")
	proto1.RegisterType((*StaticAttributes)(nil), "proto.StaticAttributes")
	proto1.RegisterType((*Commands)(nil), "proto.Commands")
	proto1.RegisterType((*IotDevice)(nil), "proto.IotDevice")
	proto1.RegisterType((*DeleteIotDeviceRequest)(nil), "proto.DeleteIotDeviceRequest")
	proto1.RegisterType((*CreateIotDeviceRequest)(nil), "proto.CreateIotDeviceRequest")
	proto1.RegisterType((*ListIotDevicesResponse)(nil), "proto.ListIotDevicesResponse")
	proto1.RegisterType((*UpdateIotDeviceRequest)(nil), "proto.UpdateIotDeviceRequest")
	proto1.RegisterType((*IotDeviceResponse)(nil), "proto.IotDeviceResponse")
	proto1.RegisterType((*IotDeviceRequest)(nil), "proto.IotDeviceRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IotDevicesService service

type IotDevicesServiceClient interface {
	DeleteIotDevice(ctx context.Context, in *DeleteIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	CreateIotDevice(ctx context.Context, in *CreateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ListIotDevices(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListIotDevicesResponse, error)
	UpdateIotDevice(ctx context.Context, in *UpdateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	IotDevice(ctx context.Context, in *IotDeviceRequest, opts ...grpc.CallOption) (*IotDeviceResponse, error)
}

type iotDevicesServiceClient struct {
	cc *grpc.ClientConn
}

func NewIotDevicesServiceClient(cc *grpc.ClientConn) IotDevicesServiceClient {
	return &iotDevicesServiceClient{cc}
}

func (c *iotDevicesServiceClient) DeleteIotDevice(ctx context.Context, in *DeleteIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/DeleteIotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) CreateIotDevice(ctx context.Context, in *CreateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/CreateIotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) ListIotDevices(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListIotDevicesResponse, error) {
	out := new(ListIotDevicesResponse)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/ListIotDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) UpdateIotDevice(ctx context.Context, in *UpdateIotDeviceRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/UpdateIotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotDevicesServiceClient) IotDevice(ctx context.Context, in *IotDeviceRequest, opts ...grpc.CallOption) (*IotDeviceResponse, error) {
	out := new(IotDeviceResponse)
	err := grpc.Invoke(ctx, "/proto.IotDevicesService/IotDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IotDevicesService service

type IotDevicesServiceServer interface {
	DeleteIotDevice(context.Context, *DeleteIotDeviceRequest) (*google_protobuf1.Empty, error)
	CreateIotDevice(context.Context, *CreateIotDeviceRequest) (*google_protobuf1.Empty, error)
	ListIotDevices(context.Context, *google_protobuf1.Empty) (*ListIotDevicesResponse, error)
	UpdateIotDevice(context.Context, *UpdateIotDeviceRequest) (*google_protobuf1.Empty, error)
	IotDevice(context.Context, *IotDeviceRequest) (*IotDeviceResponse, error)
}

func RegisterIotDevicesServiceServer(s *grpc.Server, srv IotDevicesServiceServer) {
	s.RegisterService(&_IotDevicesService_serviceDesc, srv)
}

func _IotDevicesService_DeleteIotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).DeleteIotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/DeleteIotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).DeleteIotDevice(ctx, req.(*DeleteIotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_CreateIotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).CreateIotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/CreateIotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).CreateIotDevice(ctx, req.(*CreateIotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_ListIotDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).ListIotDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/ListIotDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).ListIotDevices(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_UpdateIotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).UpdateIotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/UpdateIotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).UpdateIotDevice(ctx, req.(*UpdateIotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IotDevicesService_IotDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IotDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IotDevicesServiceServer).IotDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IotDevicesService/IotDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IotDevicesServiceServer).IotDevice(ctx, req.(*IotDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IotDevicesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IotDevicesService",
	HandlerType: (*IotDevicesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteIotDevice",
			Handler:    _IotDevicesService_DeleteIotDevice_Handler,
		},
		{
			MethodName: "CreateIotDevice",
			Handler:    _IotDevicesService_CreateIotDevice_Handler,
		},
		{
			MethodName: "ListIotDevices",
			Handler:    _IotDevicesService_ListIotDevices_Handler,
		},
		{
			MethodName: "UpdateIotDevice",
			Handler:    _IotDevicesService_UpdateIotDevice_Handler,
		},
		{
			MethodName: "IotDevice",
			Handler:    _IotDevicesService_IotDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iotDevice.proto",
}

func init() { proto1.RegisterFile("iotDevice.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xa5, 0x4d, 0xbb, 0xb5, 0xb7, 0xa8, 0x1f, 0x01, 0xba, 0xa8, 0x1b, 0x68, 0xaa, 0x84, 0x34,
	0x04, 0x4a, 0x51, 0x11, 0x4f, 0x48, 0x08, 0xd4, 0x4e, 0xa2, 0xd3, 0xc4, 0xa6, 0x0c, 0x78, 0xad,
	0xdc, 0xe6, 0xb2, 0x05, 0x35, 0x71, 0xa8, 0xdd, 0x49, 0xd9, 0x33, 0x7f, 0x95, 0xff, 0x81, 0xe2,
	0x38, 0x89, 0x93, 0x9a, 0x22, 0xa4, 0x3d, 0xb5, 0xf6, 0x3d, 0xf7, 0x9c, 0x73, 0x7d, 0x1c, 0x43,
	0xc7, 0xa3, 0x7c, 0x8a, 0xb7, 0xde, 0x12, 0xed, 0x70, 0x4d, 0x39, 0x35, 0xeb, 0xe2, 0x67, 0x70,
	0x74, 0x4d, 0xe9, 0xf5, 0x0a, 0x47, 0x24, 0xf4, 0x46, 0x24, 0x08, 0x28, 0x27, 0xdc, 0xa3, 0x01,
	0x4b, 0x40, 0x83, 0x43, 0x59, 0x15, 0xab, 0xc5, 0xe6, 0xfb, 0x08, 0xfd, 0x90, 0x47, 0xb2, 0xf8,
	0xf0, 0x96, 0xac, 0x36, 0x28, 0xa1, 0x43, 0x0a, 0xf0, 0x91, 0xf3, 0xb5, 0xb7, 0xd8, 0x70, 0x64,
	0xe6, 0x73, 0x68, 0x5c, 0x2c, 0x7e, 0xe0, 0x92, 0xcf, 0x5c, 0xab, 0x72, 0x5c, 0x39, 0x69, 0x3a,
	0x8f, 0xa8, 0x58, 0xcf, 0x3d, 0xf7, 0x15, 0xf5, 0x3d, 0x2e, 0x88, 0xcc, 0x23, 0xa8, 0x7d, 0x26,
	0x3e, 0x5a, 0x55, 0x01, 0x69, 0x07, 0xc4, 0xc7, 0x62, 0xf5, 0x4b, 0x14, 0xa2, 0x65, 0x24, 0x55,
	0x1e, 0x85, 0x4a, 0x75, 0x18, 0x40, 0xf7, 0x2a, 0x76, 0xbb, 0x54, 0x64, 0x53, 0x3e, 0x43, 0xcb,
	0xf7, 0x0c, 0xea, 0xdf, 0x62, 0xcb, 0xd2, 0x51, 0x47, 0xf8, 0xd7, 0xe8, 0x55, 0xb5, 0x7a, 0x3e,
	0x34, 0x26, 0xd4, 0xf7, 0x49, 0xe0, 0x16, 0xc7, 0x33, 0xfe, 0x3d, 0x5e, 0x65, 0xe7, 0x78, 0x7a,
	0xb9, 0xdf, 0x06, 0x34, 0x67, 0x69, 0x66, 0xb1, 0x60, 0xf2, 0x6f, 0xe6, 0x5a, 0x90, 0x08, 0xba,
	0x62, 0x5d, 0x14, 0x1c, 0xc2, 0xfe, 0x15, 0xae, 0xe3, 0x7d, 0xa9, 0xd9, 0x63, 0xc9, 0x52, 0xc1,
	0xbc, 0x84, 0x96, 0xc4, 0x5c, 0x12, 0x7e, 0x23, 0xd5, 0xfb, 0x12, 0x37, 0x0f, 0x09, 0xbf, 0x51,
	0xc0, 0x2f, 0x00, 0x4e, 0x03, 0xee, 0xf1, 0x48, 0x39, 0xd6, 0x27, 0x28, 0x76, 0xe6, 0xa5, 0x71,
	0x32, 0xa8, 0x18, 0xaa, 0x56, 0x80, 0x16, 0x67, 0x33, 0xdf, 0x01, 0x90, 0x2c, 0x34, 0xab, 0x7e,
	0x6c, 0x9c, 0xb4, 0xc6, 0xbd, 0xe4, 0x1e, 0xd9, 0x79, 0x9a, 0xce, 0xe3, 0x1c, 0x54, 0xd0, 0xa9,
	0xad, 0xc8, 0x5d, 0x64, 0xed, 0x89, 0xb6, 0x96, 0x6c, 0x3b, 0x27, 0x77, 0x91, 0xd3, 0x8e, 0x0b,
	0x0a, 0xf4, 0x2d, 0x34, 0x96, 0x32, 0x32, 0x6b, 0x5f, 0xc0, 0x3b, 0x12, 0x9e, 0x26, 0xe9, 0x98,
	0x29, 0x40, 0x69, 0xbb, 0x80, 0x1e, 0x13, 0x37, 0x6b, 0xae, 0xb8, 0x6c, 0x88, 0xfe, 0x03, 0xd9,
	0x5f, 0xbe, 0x79, 0xce, 0xe1, 0x56, 0x87, 0x42, 0x38, 0x80, 0xc6, 0x65, 0xdc, 0xb6, 0xa4, 0x2b,
	0xab, 0x29, 0x0e, 0x26, 0x5b, 0x0f, 0xa7, 0xd0, 0x9f, 0xe2, 0x0a, 0x39, 0x66, 0x61, 0x3b, 0xf8,
	0x73, 0x83, 0x8c, 0x9b, 0x6d, 0xa8, 0x66, 0x5f, 0x4f, 0x75, 0xe6, 0x16, 0x58, 0xaa, 0x25, 0x96,
	0x4f, 0xd0, 0x9f, 0xac, 0x91, 0x68, 0x58, 0x6c, 0xe5, 0x1a, 0x09, 0xb2, 0xd6, 0xb8, 0x2b, 0x87,
	0xc8, 0xb1, 0x39, 0x64, 0x78, 0x06, 0xfd, 0x73, 0x8f, 0xf1, 0x6c, 0x83, 0x39, 0xc8, 0x42, 0x1a,
	0x30, 0x34, 0x5f, 0x03, 0xe4, 0xbb, 0x56, 0x45, 0x9c, 0xc7, 0x36, 0x95, 0x82, 0x89, 0x5d, 0x7d,
	0x0d, 0xdd, 0xfb, 0x70, 0x35, 0x81, 0x9e, 0xc2, 0x21, 0x0d, 0xfd, 0x2f, 0xc9, 0x7b, 0xe8, 0x6a,
	0x0f, 0x79, 0x9a, 0x1d, 0xf2, 0x74, 0xd7, 0x21, 0x8f, 0x7f, 0x19, 0x8a, 0x0b, 0x26, 0x3f, 0x22,
	0xf3, 0x0c, 0x3a, 0xa5, 0x00, 0xcd, 0xa7, 0xd2, 0x85, 0x3e, 0xd8, 0x41, 0xdf, 0x4e, 0x9e, 0x55,
	0x3b, 0x7d, 0x56, 0xed, 0x53, 0xf1, 0xc9, 0x3f, 0x88, 0xb9, 0x4a, 0x31, 0x66, 0x5c, 0xfa, 0x78,
	0x77, 0x70, 0xcd, 0xa0, 0x5d, 0x0c, 0xd2, 0xfc, 0x0b, 0x76, 0x90, 0x4a, 0xe8, 0x73, 0x4f, 0x6c,
	0x95, 0x72, 0xcc, 0x6c, 0xe9, 0xf3, 0xdd, 0x61, 0xeb, 0x83, 0xfa, 0xac, 0x1d, 0x6c, 0xc5, 0x25,
	0xfb, 0xad, 0xed, 0x42, 0xea, 0x66, 0xb1, 0x27, 0x4a, 0x6f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x2e, 0x17, 0xa6, 0xa7, 0xd3, 0x06, 0x00, 0x00,
}
