// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serviceGroup.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ServiceGroup struct {
	// @inject_tag: json:"api_key,omitempty" bson:"api_key"
	ApiKey string `protobuf:"bytes,1,opt,name=ApiKey,json=api_key,omitempty" json:"api_key,omitempty" bson:"api_key"`
	// @inject_tag: json:"entity_type,omitempty" bson:"entity_type"
	EntityType string `protobuf:"bytes,2,opt,name=EntityType,json=entity_type,omitempty" json:"entity_type,omitempty" bson:"entity_type"`
	// @inject_tag: json:"resource,omitempty" bson:"resource"
	Resource string `protobuf:"bytes,3,opt,name=Resource,json=resource,omitempty" json:"resource,omitempty" bson:"resource"`
	// @inject_tag: json:"commands,omitempty" bson:"commands"
	Commands []*Command `protobuf:"bytes,4,rep,name=Commands,json=commands,omitempty" json:"commands,omitempty" bson:"commands"`
	// @inject_tag: json:"attributes,omitempty" bson:"attributes"
	Attributes []*Attribute `protobuf:"bytes,5,rep,name=Attributes,json=attributes,omitempty" json:"attributes,omitempty" bson:"attributes"`
	// @inject_tag: json:"static_attributes,omitempty" bson:"static_attributes"
	StaticAttributes []*StaticAttribute `protobuf:"bytes,6,rep,name=StaticAttributes,json=static_attributes,omitempty" json:"static_attributes,omitempty" bson:"static_attributes"`
	// @inject_tag: json:"lazy,omitempty" bson:"lazy"
	Lazy []*Lazy `protobuf:"bytes,7,rep,name=Lazy,json=lazy,omitempty" json:"lazy,omitempty" bson:"lazy"`
	// @inject_tag: json:"service,omitempty" bson:"service"
	Service string `protobuf:"bytes,8,opt,name=Service,json=service,omitempty" json:"service,omitempty" bson:"service"`
	// @inject_tag: json:"subservice,omitempty" bson:"subservice"
	Subservice string `protobuf:"bytes,9,opt,name=Subservice,json=subservice,omitempty" json:"subservice,omitempty" bson:"subservice"`
	// @inject_tag: json:"_id,omitempty" bson:"_id"
	ID string `protobuf:"bytes,10,opt,name=ID,json=_id,omitempty" json:"_id,omitempty" bson:"_id"`
	// @inject_tag: json:"protocol,omitempty" bson:"protocol"
	Protocol string `protobuf:"bytes,11,opt,name=Protocol,json=protocol, omitempty" json:"protocol,omitempty" bson:"protocol"`
}

func (m *ServiceGroup) Reset()                    { *m = ServiceGroup{} }
func (m *ServiceGroup) String() string            { return proto1.CompactTextString(m) }
func (*ServiceGroup) ProtoMessage()               {}
func (*ServiceGroup) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *ServiceGroup) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *ServiceGroup) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *ServiceGroup) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *ServiceGroup) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *ServiceGroup) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ServiceGroup) GetStaticAttributes() []*StaticAttribute {
	if m != nil {
		return m.StaticAttributes
	}
	return nil
}

func (m *ServiceGroup) GetLazy() []*Lazy {
	if m != nil {
		return m.Lazy
	}
	return nil
}

func (m *ServiceGroup) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceGroup) GetSubservice() string {
	if m != nil {
		return m.Subservice
	}
	return ""
}

func (m *ServiceGroup) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ServiceGroup) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type Command struct {
	// @inject_tag: json:"name,omitempty" bson:"name"
	Name string `protobuf:"bytes,1,opt,name=Name,json=name" json:"name,omitempty" bson:"name"`
	// @inject_tag: json:"type,omitempty" bson:"type"
	Type string `protobuf:"bytes,2,opt,name=Type,json=type" json:"type,omitempty" bson:"type"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto1.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Attribute struct {
	// @inject_tag: json:"object_id,omitempty" bson:"object_id"
	ObjectID string `protobuf:"bytes,1,opt,name=ObjectID,json=object_id" json:"object_id,omitempty" bson:"object_id"`
	// @inject_tag: json:"name,omitempty" bson:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,json=name" json:"name,omitempty" bson:"name"`
	// @inject_tag: json:"type,omitempty" bson:"type"
	Type string `protobuf:"bytes,3,opt,name=Type,json=type" json:"type,omitempty" bson:"type"`
}

func (m *Attribute) Reset()                    { *m = Attribute{} }
func (m *Attribute) String() string            { return proto1.CompactTextString(m) }
func (*Attribute) ProtoMessage()               {}
func (*Attribute) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Attribute) GetObjectID() string {
	if m != nil {
		return m.ObjectID
	}
	return ""
}

func (m *Attribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Attribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type StaticAttribute struct {
	// @inject_tag: json:"value,omitempty" bson:"value"
	Value string `protobuf:"bytes,1,opt,name=Value,json=value" json:"value,omitempty" bson:"value"`
	// @inject_tag: json:"name,omitempty" bson:"name"
	Name string `protobuf:"bytes,2,opt,name=Name,json=name" json:"name,omitempty" bson:"name"`
	// @inject_tag: json:"type,omitempty" bson:"type"
	Type string `protobuf:"bytes,3,opt,name=Type,json=type" json:"type,omitempty" bson:"type"`
}

func (m *StaticAttribute) Reset()                    { *m = StaticAttribute{} }
func (m *StaticAttribute) String() string            { return proto1.CompactTextString(m) }
func (*StaticAttribute) ProtoMessage()               {}
func (*StaticAttribute) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *StaticAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StaticAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StaticAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type DeleteServiceGroupRequest struct {
	ServiceGroup *ServiceGroup `protobuf:"bytes,1,opt,name=serviceGroup" json:"serviceGroup,omitempty"`
}

func (m *DeleteServiceGroupRequest) Reset()                    { *m = DeleteServiceGroupRequest{} }
func (m *DeleteServiceGroupRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteServiceGroupRequest) ProtoMessage()               {}
func (*DeleteServiceGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *DeleteServiceGroupRequest) GetServiceGroup() *ServiceGroup {
	if m != nil {
		return m.ServiceGroup
	}
	return nil
}

type CreateServiceGroupRequest struct {
	ServiceGroup *ServiceGroup `protobuf:"bytes,1,opt,name=serviceGroup" json:"serviceGroup,omitempty"`
}

func (m *CreateServiceGroupRequest) Reset()                    { *m = CreateServiceGroupRequest{} }
func (m *CreateServiceGroupRequest) String() string            { return proto1.CompactTextString(m) }
func (*CreateServiceGroupRequest) ProtoMessage()               {}
func (*CreateServiceGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *CreateServiceGroupRequest) GetServiceGroup() *ServiceGroup {
	if m != nil {
		return m.ServiceGroup
	}
	return nil
}

type ListServiceGroupsResponse struct {
	ServiceGroup []*ServiceGroup `protobuf:"bytes,1,rep,name=serviceGroup" json:"serviceGroup,omitempty"`
}

func (m *ListServiceGroupsResponse) Reset()                    { *m = ListServiceGroupsResponse{} }
func (m *ListServiceGroupsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListServiceGroupsResponse) ProtoMessage()               {}
func (*ListServiceGroupsResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *ListServiceGroupsResponse) GetServiceGroup() []*ServiceGroup {
	if m != nil {
		return m.ServiceGroup
	}
	return nil
}

type UpdateServiceGroupRequest struct {
	ServiceGroup *ServiceGroup `protobuf:"bytes,1,opt,name=serviceGroup" json:"serviceGroup,omitempty"`
}

func (m *UpdateServiceGroupRequest) Reset()                    { *m = UpdateServiceGroupRequest{} }
func (m *UpdateServiceGroupRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateServiceGroupRequest) ProtoMessage()               {}
func (*UpdateServiceGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *UpdateServiceGroupRequest) GetServiceGroup() *ServiceGroup {
	if m != nil {
		return m.ServiceGroup
	}
	return nil
}

type ServiceGroupResponse struct {
	ServiceGroup *ServiceGroup `protobuf:"bytes,1,opt,name=serviceGroup" json:"serviceGroup,omitempty"`
}

func (m *ServiceGroupResponse) Reset()                    { *m = ServiceGroupResponse{} }
func (m *ServiceGroupResponse) String() string            { return proto1.CompactTextString(m) }
func (*ServiceGroupResponse) ProtoMessage()               {}
func (*ServiceGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *ServiceGroupResponse) GetServiceGroup() *ServiceGroup {
	if m != nil {
		return m.ServiceGroup
	}
	return nil
}

type ServiceGroupRequest struct {
	Protocol string `protobuf:"bytes,1,opt,name=Protocol" json:"Protocol,omitempty"`
	ID       string `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty"`
}

func (m *ServiceGroupRequest) Reset()                    { *m = ServiceGroupRequest{} }
func (m *ServiceGroupRequest) String() string            { return proto1.CompactTextString(m) }
func (*ServiceGroupRequest) ProtoMessage()               {}
func (*ServiceGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *ServiceGroupRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ServiceGroupRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto1.RegisterType((*ServiceGroup)(nil), "proto.ServiceGroup")
	proto1.RegisterType((*Command)(nil), "proto.Command")
	proto1.RegisterType((*Attribute)(nil), "proto.Attribute")
	proto1.RegisterType((*StaticAttribute)(nil), "proto.StaticAttribute")
	proto1.RegisterType((*DeleteServiceGroupRequest)(nil), "proto.DeleteServiceGroupRequest")
	proto1.RegisterType((*CreateServiceGroupRequest)(nil), "proto.CreateServiceGroupRequest")
	proto1.RegisterType((*ListServiceGroupsResponse)(nil), "proto.ListServiceGroupsResponse")
	proto1.RegisterType((*UpdateServiceGroupRequest)(nil), "proto.UpdateServiceGroupRequest")
	proto1.RegisterType((*ServiceGroupResponse)(nil), "proto.ServiceGroupResponse")
	proto1.RegisterType((*ServiceGroupRequest)(nil), "proto.ServiceGroupRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ServiceGroupsService service

type ServiceGroupsServiceClient interface {
	DeleteServiceGroup(ctx context.Context, in *DeleteServiceGroupRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	CreateServiceGroup(ctx context.Context, in *CreateServiceGroupRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ListServiceGroups(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListServiceGroupsResponse, error)
	UpdateServiceGroup(ctx context.Context, in *UpdateServiceGroupRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ServiceGroup(ctx context.Context, in *ServiceGroupRequest, opts ...grpc.CallOption) (*ServiceGroupResponse, error)
}

type serviceGroupsServiceClient struct {
	cc *grpc.ClientConn
}

func NewServiceGroupsServiceClient(cc *grpc.ClientConn) ServiceGroupsServiceClient {
	return &serviceGroupsServiceClient{cc}
}

func (c *serviceGroupsServiceClient) DeleteServiceGroup(ctx context.Context, in *DeleteServiceGroupRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.ServiceGroupsService/DeleteServiceGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceGroupsServiceClient) CreateServiceGroup(ctx context.Context, in *CreateServiceGroupRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.ServiceGroupsService/CreateServiceGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceGroupsServiceClient) ListServiceGroups(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*ListServiceGroupsResponse, error) {
	out := new(ListServiceGroupsResponse)
	err := grpc.Invoke(ctx, "/proto.ServiceGroupsService/ListServiceGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceGroupsServiceClient) UpdateServiceGroup(ctx context.Context, in *UpdateServiceGroupRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/proto.ServiceGroupsService/UpdateServiceGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceGroupsServiceClient) ServiceGroup(ctx context.Context, in *ServiceGroupRequest, opts ...grpc.CallOption) (*ServiceGroupResponse, error) {
	out := new(ServiceGroupResponse)
	err := grpc.Invoke(ctx, "/proto.ServiceGroupsService/ServiceGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceGroupsService service

type ServiceGroupsServiceServer interface {
	DeleteServiceGroup(context.Context, *DeleteServiceGroupRequest) (*google_protobuf1.Empty, error)
	CreateServiceGroup(context.Context, *CreateServiceGroupRequest) (*google_protobuf1.Empty, error)
	ListServiceGroups(context.Context, *google_protobuf1.Empty) (*ListServiceGroupsResponse, error)
	UpdateServiceGroup(context.Context, *UpdateServiceGroupRequest) (*google_protobuf1.Empty, error)
	ServiceGroup(context.Context, *ServiceGroupRequest) (*ServiceGroupResponse, error)
}

func RegisterServiceGroupsServiceServer(s *grpc.Server, srv ServiceGroupsServiceServer) {
	s.RegisterService(&_ServiceGroupsService_serviceDesc, srv)
}

func _ServiceGroupsService_DeleteServiceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceGroupsServiceServer).DeleteServiceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceGroupsService/DeleteServiceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceGroupsServiceServer).DeleteServiceGroup(ctx, req.(*DeleteServiceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceGroupsService_CreateServiceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceGroupsServiceServer).CreateServiceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceGroupsService/CreateServiceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceGroupsServiceServer).CreateServiceGroup(ctx, req.(*CreateServiceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceGroupsService_ListServiceGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceGroupsServiceServer).ListServiceGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceGroupsService/ListServiceGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceGroupsServiceServer).ListServiceGroups(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceGroupsService_UpdateServiceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceGroupsServiceServer).UpdateServiceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceGroupsService/UpdateServiceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceGroupsServiceServer).UpdateServiceGroup(ctx, req.(*UpdateServiceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceGroupsService_ServiceGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceGroupsServiceServer).ServiceGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ServiceGroupsService/ServiceGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceGroupsServiceServer).ServiceGroup(ctx, req.(*ServiceGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceGroupsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ServiceGroupsService",
	HandlerType: (*ServiceGroupsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteServiceGroup",
			Handler:    _ServiceGroupsService_DeleteServiceGroup_Handler,
		},
		{
			MethodName: "CreateServiceGroup",
			Handler:    _ServiceGroupsService_CreateServiceGroup_Handler,
		},
		{
			MethodName: "ListServiceGroups",
			Handler:    _ServiceGroupsService_ListServiceGroups_Handler,
		},
		{
			MethodName: "UpdateServiceGroup",
			Handler:    _ServiceGroupsService_UpdateServiceGroup_Handler,
		},
		{
			MethodName: "ServiceGroup",
			Handler:    _ServiceGroupsService_ServiceGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceGroup.proto",
}

func init() { proto1.RegisterFile("serviceGroup.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0x86, 0xbf, 0x60, 0x48, 0x60, 0xc8, 0x97, 0x26, 0x1b, 0x1a, 0x39, 0xa6, 0x07, 0x8a, 0x5a,
	0x89, 0x48, 0x11, 0xa8, 0xb4, 0x52, 0xa5, 0xde, 0x50, 0x88, 0x2a, 0xd4, 0xb4, 0x20, 0x93, 0xf6,
	0x8a, 0x16, 0x33, 0x8d, 0xdc, 0x62, 0xaf, 0xeb, 0x5d, 0x47, 0x72, 0x7e, 0x51, 0x7f, 0x65, 0x55,
	0x79, 0xbd, 0xb8, 0x0b, 0xd8, 0x11, 0x87, 0x9c, 0xd0, 0xcc, 0xbc, 0xf3, 0x78, 0x34, 0xf3, 0xda,
	0x00, 0xe1, 0x18, 0xde, 0xbb, 0x0e, 0x7e, 0x0c, 0x59, 0x14, 0x74, 0x83, 0x90, 0x09, 0x46, 0x2a,
	0xf2, 0xc7, 0x7a, 0x71, 0xc7, 0xd8, 0xdd, 0x12, 0x7b, 0x34, 0x70, 0x7b, 0xd4, 0xf7, 0x99, 0xa0,
	0xc2, 0x65, 0x3e, 0x4f, 0x45, 0x56, 0x53, 0x55, 0x65, 0x34, 0x8f, 0xbe, 0xf7, 0xd0, 0x0b, 0x44,
	0xac, 0x8a, 0x87, 0xf7, 0x74, 0x19, 0xa1, 0x92, 0xb6, 0xff, 0x18, 0x70, 0x38, 0xd5, 0x1e, 0x43,
	0x5e, 0xc2, 0xfe, 0x20, 0x70, 0x3f, 0x61, 0x6c, 0xee, 0xb5, 0xf6, 0x3a, 0x35, 0xfb, 0x84, 0x06,
	0xee, 0xec, 0x27, 0xc6, 0x97, 0xcc, 0x73, 0x85, 0xe4, 0x90, 0x0b, 0x80, 0x6b, 0x5f, 0xb8, 0x22,
	0xbe, 0x8d, 0x03, 0x34, 0x4b, 0x52, 0xf6, 0x1c, 0x65, 0x66, 0x26, 0xe2, 0x00, 0x35, 0xe9, 0x2b,
	0xa8, 0xda, 0xc8, 0x59, 0x14, 0x3a, 0x68, 0x1a, 0x52, 0x48, 0x42, 0x15, 0x6b, 0xaa, 0x77, 0x50,
	0xbd, 0x62, 0x9e, 0x47, 0xfd, 0x05, 0x37, 0xcb, 0x2d, 0xa3, 0x53, 0xef, 0x1f, 0xa5, 0xe3, 0x75,
	0x55, 0xda, 0x26, 0x8e, 0xaa, 0x6b, 0x5d, 0x1f, 0x00, 0x06, 0x42, 0x84, 0xee, 0x3c, 0x12, 0xc8,
	0xcd, 0x8a, 0xec, 0x3b, 0x56, 0x7d, 0x59, 0xc1, 0x6e, 0xd0, 0x4c, 0xa3, 0xf5, 0x7e, 0x86, 0xe3,
	0x69, 0xb2, 0x33, 0x47, 0x23, 0xec, 0x4b, 0xc2, 0x99, 0x22, 0x6c, 0x94, 0xed, 0x26, 0x97, 0x89,
	0x59, 0x2e, 0xee, 0x02, 0xca, 0x37, 0xf4, 0x21, 0x36, 0x0f, 0x24, 0xa2, 0xae, 0x10, 0x49, 0xca,
	0x3e, 0x5a, 0xd2, 0x07, 0x7d, 0x79, 0x6d, 0x38, 0x50, 0xfb, 0x36, 0xab, 0xe9, 0x82, 0xd5, 0x95,
	0x35, 0x4d, 0x07, 0x60, 0x1a, 0xcd, 0x55, 0xde, 0xac, 0x49, 0x59, 0x83, 0x67, 0x19, 0x4d, 0x79,
	0x0e, 0xa5, 0xd1, 0xd0, 0x04, 0xa9, 0xf8, 0x7f, 0xe6, 0x2e, 0xb4, 0xd2, 0x6b, 0xa8, 0x4e, 0x92,
	0x31, 0x1c, 0xb6, 0x34, 0xeb, 0x52, 0x70, 0x1a, 0xa8, 0xf8, 0xb2, 0x95, 0xc9, 0xda, 0x6f, 0xe0,
	0x40, 0x2d, 0x99, 0x10, 0x28, 0x7f, 0xa1, 0x1e, 0xaa, 0xc3, 0x97, 0x7d, 0xea, 0x61, 0x92, 0xd3,
	0xae, 0x5c, 0x4e, 0xce, 0xdb, 0x9e, 0x40, 0x2d, 0xdb, 0x0b, 0x69, 0x42, 0x75, 0x3c, 0xff, 0x81,
	0x8e, 0x18, 0x0d, 0x55, 0x63, 0x8d, 0xc9, 0x78, 0xe6, 0xfe, 0x23, 0x96, 0x72, 0x88, 0x86, 0x46,
	0x1c, 0xc3, 0xb3, 0x8d, 0x7d, 0x93, 0x06, 0x54, 0xbe, 0x25, 0x46, 0x55, 0xd0, 0x8a, 0x74, 0xed,
	0xce, 0xc0, 0x5b, 0x38, 0x1f, 0xe2, 0x12, 0x05, 0xea, 0xde, 0xb6, 0xf1, 0x57, 0x84, 0x5c, 0x90,
	0xf7, 0x70, 0xa8, 0xbf, 0x59, 0xf2, 0x09, 0xf5, 0xfe, 0xe9, 0xea, 0xf0, 0x7a, 0xc7, 0x9a, 0x30,
	0xa1, 0x5e, 0x85, 0x48, 0x9f, 0x9e, 0x7a, 0xe3, 0x72, 0xa1, 0x2b, 0xb8, 0x8d, 0x3c, 0x60, 0x3e,
	0xc7, 0x1c, 0xaa, 0xb1, 0x33, 0xf5, 0x6b, 0xb0, 0x78, 0xea, 0x59, 0xc7, 0xd0, 0x58, 0xe7, 0x15,
	0x8e, 0xb9, 0x23, 0x70, 0x00, 0xa7, 0x79, 0x03, 0x5a, 0x9a, 0x79, 0x53, 0x03, 0x64, 0x31, 0x39,
	0x92, 0x9e, 0x4f, 0x1d, 0x50, 0x1a, 0x0d, 0xfb, 0xbf, 0x8d, 0xf5, 0xa1, 0xb8, 0x0a, 0xc8, 0x04,
	0xc8, 0xb6, 0x09, 0x48, 0x4b, 0x0d, 0x55, 0xe8, 0x0f, 0xeb, 0xac, 0x9b, 0x7e, 0x3f, 0xbb, 0xab,
	0xef, 0x67, 0xf7, 0x5a, 0xbe, 0x2a, 0xff, 0x25, 0xc4, 0x6d, 0x03, 0x64, 0xc4, 0x42, 0x6f, 0x3c,
	0x42, 0x1c, 0xc3, 0xc9, 0xd6, 0xf1, 0x49, 0x81, 0xdc, 0x5a, 0x3d, 0xa8, 0xd0, 0x2e, 0xe9, 0x88,
	0xdb, 0x77, 0xcf, 0x46, 0x2c, 0xb4, 0xc4, 0x23, 0x23, 0x8e, 0x36, 0xfe, 0x21, 0xac, 0xbc, 0xab,
	0x2a, 0x4a, 0x33, 0xb7, 0xb6, 0x1a, 0x6e, 0xbe, 0x2f, 0xab, 0x6f, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x95, 0x93, 0x3f, 0x3c, 0xda, 0x06, 0x00, 0x00,
}
